  site: DavideBri
  title: DavideBri
  description: >-
    just a personal blog
  lang: en-US
  timezone: Rome
  repo: https://github.com/DavideBri/DavideBri.github.io # site repo [optional]
  data-theme: dark # default theme "dark" | "light"

  author:
  name: DavideBri
  bio: just a minimalist, personal blog
  username: DavideBri # general username
  github: DavideBri # github username
  twitter: DavideBri # twitter username
  email: davidebrienza@pm.me

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "webcomtop.github.io" #
baseurl: # leave blank if not wishd
permalink: "webcomtop.github.io/"
permalink: pretty 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->", "<!---", "--->"]
  ignore:
    envs: all

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
